apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-four-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-four
  template:
    metadata:
      labels:
        app: consumer-four
    spec:
      containers:
        - name: consumer-four
          image: raorajath/python-consumer-four:latest
          ports:
            - containerPort: 5000
---
